/*drop table GroupsLectures;
drop table groupscurators;
drop table Lectures;
drop table Teachers;
drop table Subjects;
drop table curators;
drop table groups;
drop table departments;
drop table faculties;*/

create table faculties(
                          id integer PRIMARY KEY generated by default as identity,
                          name varchar(100) not null check ( name <> '') unique,
                          financing numeric not null check (financing >= 0) default 0
);

create table departments(
                            id integer PRIMARY KEY generated by default as identity,
                            name varchar(100) not null check ( name <> '') unique,
                            financing numeric not null check (financing >= 0) default 0,
                            faculty_id integer not null references faculties
);

create table groups(
                       id integer PRIMARY KEY generated by default as identity,
                       name varchar(10) not null check ( name <> '') unique,
                       year integer not null check ( year between 1 and 5),
                       department_id integer not null references departments
);

create table Curators
(
    Id int not null generated by default as identity primary key,
    Name varchar not null check (Name <> ''),
    Surname varchar not null check (Surname <> '')
);

create table Subjects
(
    Id int not null generated by default as identity primary key,
    Name varchar(100) not null unique check (Name <> '')
);

create table Teachers
(
    Id int not null generated by default as identity primary key,
    Name varchar not null check (Name <> ''),
    Salary numeric not null check (Salary > 0.0),
    Surname varchar not null check (Surname <> '')
);

create table Lectures
(
    Id int not null generated by default as identity primary key,
    LectureRoom varchar not null check (LectureRoom <> ''),
    SubjectId int not null references Subjects,
    TeacherId int not null references Teachers
);

create table GroupsCurators
(
    Id int not null generated by default as identity primary key,
    CuratorId int not null references Curators,
    GroupId int not null references groups
);

create table GroupsLectures
(
    Id int not null generated by default as identity primary key,
    GroupId int not null references groups,
    LectureId int not null references Lectures
);

insert into faculties (name, financing)
values ('Computer Science', 100000.00),
       ('Humanities', 15000);

insert into departments (name, financing, faculty_id)
values ('Programming Systems and DataBases', 25000, 1),
       ('Network Technologies', 25500, 1),
       ('Foreign Languages', 10000, 2),
       ('Psychology', 10000, 2);

insert into departments (name, financing, faculty_id)
values ('Department of Digital Technologies', 250000, 1),
       ('English Language', 22000, 2);


insert into groups (name, year, department_id)
values ('PSD51', 5, 1),
       ('NT32', 3, 2),
       ('FL23', 2, 3),
       ('P107', 1, 4);

insert into groups (name, year, department_id)
values ('PD31', 3, 1),
       ('NT12', 1, 2),
       ('FL41', 4, 3),
       ('P21', 2, 4);

insert into groups (name, year, department_id)
values ('FL52', 5, 3),
       ('P51', 5, 4);

insert into curators(name, surname) VALUES ('Curator of', 'PSD51'),
                                           ('Curator of', 'NT32 and P107');

insert into groupscurators (CuratorId, GroupId)
VALUES (1, 1),
       (2, 2),
       (2, 4);

insert into subjects (name)
values ('DataBase Theory');

insert into subjects (name)
values ('Information');

insert into teachers (Name, Salary, Surname)
VALUES ('Samantha', 200,'Adams');

insert into teachers (Name, Salary, Surname)
VALUES ('Peter', 300,'Parker');

insert into teachers (Name, Salary, Surname)
VALUES ('Toni', 400,'Stark');

insert into lectures (LectureRoom, SubjectId, TeacherId)
VALUES ('B103', 1, 1);

insert into lectures (LectureRoom, SubjectId, TeacherId)
VALUES ('B103', 2, 3);

insert into lectures (LectureRoom, SubjectId, TeacherId)
VALUES ('B204', 1, 1);

insert into lectures (LectureRoom, SubjectId, TeacherId)
values ('P107', 2, 2),
       ('P107', 1, 1);

insert into lectures (LectureRoom, SubjectId, TeacherId)
VALUES ('B204', 2, 1);

insert into groupslectures (GroupId, LectureId)
VALUES (4, 2),
       (4, 3);

insert into groupslectures (GroupId, LectureId)
VALUES (2, 2);

insert into groupslectures (GroupId, LectureId)
VALUES (5, 7),
       (3, 1),
       (8, 7);

/*1*/
select t.name || t.surname as full_name, g.name as groups
from teachers as t, groups as g;

/*2*/
select f.name
from departments as d, faculties as f
where d.faculty_id = f.id and d.financing > f.financing;

/*3*/
select c.name || ' ' || c.Surname, g.name
from groups as g, curators as c, groupscurators as gc
where g.id = gc.GroupId and c.id = gc.CuratorId;

/*4*/
select Teachers.Name || ' ' || Teachers.Surname
from teachers, lectures, groupslectures, groups
where Teachers.id = Lectures.TeacherId
  and Lectures.Id = GroupsLectures.LectureId
  and groups.id = GroupsLectures.GroupId
  and groups.name = 'P107';

/*5*/
select t.Name || ' ' || t.Surname as Full_name, f.name as faculty
from Teachers as t, lectures as l, groupslectures as gl, groups as g, departments as d, faculties as f
where t.id = l.teacherid
  and l.id = gl.lectureid
  and g.id = gl.GroupId
  and g.department_id = d.id
  and d.faculty_id = f.id;

/*6*/
select d.name as "Название кафедры", g.name as "Название группы"
from departments as d, groups as g
where g.department_id = d.id
order by d.name;

/*7*/
select s.name
from subjects as s, lectures as l, teachers as t
where s.id = l.subjectid
  and l.teacherid = t.id
  and t.name = 'Samantha'
  and t.surname = 'Adams'
group by s.name;

/*8*/
select d.name
from subjects as s, lectures as l, groupslectures as gl, groups as g, departments as d
where s.id = l.subjectid
  and l.id = gl.lectureid
  and gl.groupid = g.id
  and g.department_id = d.id
  and s.name = 'DataBase Theory';

/*9*/
select g.name as groups_name
from groups as g, departments as d, faculties as f
where g.department_id = d.id
  and d.faculty_id = f.id
  and f.name = 'Computer Science';

/*10*/
select g.name as groups_name, f.name as faculties_name
from groups as g, departments as d, faculties as f
where g.department_id = d.id
  and d.faculty_id = f.id
  and g.year = 5;

/*11*/
select t.Name || ' ' || t.surname as full_name, s.name as subject, g.name as groups_name
from teachers as t, lectures as l, subjects as s, groupslectures as gl, groups as g
where t.id = l.teacherid
  and l.subjectid = s.id
  and l.id = gl.lectureid
  and gl.groupid = g.id
  and l.lectureroom = 'B103';
