create database book_shop;

create table countries (
    id integer primary key generated by default as identity not null,
    name varchar(50) not null check (name != '') unique
);

create table authors (
    id integer primary key generated by default as identity not null ,
    name varchar not null check (name != ''),
    surname varchar not null check (surname != '')
);

alter table authors add column country_id integer not null references countries;

create table theme (
    id integer primary key generated by default as identity not null,
    name varchar(100) not null check (name != '') unique
);

create table books (
    id integer primary key generated by default as identity not null,
    name varchar not null check (name != ''),
    pages integer not null check (pages > 0),
    price numeric not null check (price >= 0),
    publish_date date not null check (publish_date <= now()),
    author_id integer not null references authors,
    theme_id integer not null references theme
);

create table shops (
    id integer primary key generated by default as identity not null,
    name varchar not null check (name != ''),
    country_id integer not null references countries
);

create table sales (
    id integer primary key generated by default as identity not null,
    price numeric not null check (price >= 0),
    quantity integer not null check (quantity > 0),
    sale_date date not null check (sale_date <= now()) default now(),
    book_id integer not null references books,
    shop_id integer not null references shops
);

insert into countries (name)
values ('США'),
       ('Россия'),
       ('Украина'),
       ('Франция'),
       ('Англия');

insert into authors (name, surname, country_id)
values ('Стивен', 'Кинг', 1),
       ('Федор', 'Достоевский', 2),
       ('Николай', 'Гоголь', 3),
       ('Виктор', 'Гюго', 4),
       ('Агата', 'Кристи', 5),
       ('Брюс', 'Эккель', 1),
       ('Барри', 'Берд', 1),
       ('Виктор', 'Папанек', 3),
       ('Томас', 'Лимончелли', 4);

insert into shops (name, country_id)
VALUES ('Читай-город', 2),
       ('Почитайка', 3),
       ('Американ-экспресс', 1),
       ('Таймс', 5),
       ('Башня', 4);

insert into theme (name)
values ('Мистика'),
       ('Классика'),
       ('Детектив'),
       ('Программирование'),
       ('Дизайн'),
       ('Администрирование');

insert into books (name, pages, price, publish_date, author_id, theme_id)
values ('Под куполом', 530, 780, '2005.11.06', 1, 1),
       ('Преступление и наказание', 400, 950, '1887.05.14', 2, 2),
       ('Мертвые души', 380, 600, '1874.12.01', 3, 2),
       ('Собор Парижской Богоматери', 530, 1000, '1831.05.16', 4, 2),
       ('Убийство в Восточном экспрессе', 340, 8000, '1934.01.01', 5, 3),
       ('Философия Java', 630, 1200, '2017.10.10', 6, 4),
       ('Java для чайников', 630, 580, '2007.09.15', 7, 4),
       ('Дизайн для реального мира', 720, 1300, '2008.01.06', 8, 5),
       ('Тайм-менеджмент для системных администраторов', 830, 1400, '2014.01.02', 9, 6);

insert into books (name, pages, price, publish_date, author_id, theme_id)
values ('Азбука', 95, 250, '1977.11.01', 2, 2),
       ('Заблуждение', 358, 420, '1998.08.25', 5, 3);

insert into sales (price, quantity, book_id, shop_id)
values (780, 2, 1, 3),
       (950, 5, 2, 1),
       (950, 4, 2, 2),
       (600, 1, 3, 1),
       (600, 3, 3, 4),
       (580, 4, 7, 1),
       (580, 7, 7, 5),
       (580, 1, 7, 3),
       (1400, 2, 9, 2),
       (1400, 5, 9, 4);

/*Задание 2*/

select *
from books
where name like 'А%' or name like 'З%';

/*Задание 6*/

select *
from books
where regexp_count(name, ' ') = 3;

/*Задание 7.2*/
select b.name as Название, s.price as цена, s.quantity as продано_штук, t.name as жанр, s.shop_id as магазин
from theme t
left join books b on t.id = b.theme_id
left join sales s on b.id = s.book_id
where t.name != 'Программирование';

/*Задание 7.6*/
select books.name, shops.name, sales.price, sales.quantity, sales.sale_date, countries.name
from sales, books, shops, countries
where countries.id = shops.country_id
and shops.id = sales.shop_id
and sales.book_id = books.id
and countries.name != 'Россия'
and countries.name != 'Украина';

select b.name, s.name, s2.price, s2.quantity, s2.sale_date, c.name
from countries c
join shops s on c.id = s.country_id
join sales s2 on s.id = s2.shop_id
join books b on b.id = s2.book_id
where (c.name != 'Россия' and c.name != 'Украина');


/*Задание 8*/

select 'Количество авторов', count(authors.id)
from authors;

select 'Количество книг', count(books.id)
from books;

select 'Средняя цена продажи', avg(books.price)
from books;

select 'Среднее количество страниц', avg(books.pages)
from books;

/*Задание 13*/

select theme.name, sum(books.pages)
from books, theme
where theme.id = books.theme_id
and books.pages > 400
and (theme.name = 'Программирование'
or theme.name = 'Администрирование'
or theme.name = 'Дизайн')
group by theme.name;

/*Задание 15*/

create  view view_sales as
select shops.id as name, sum(sales.quantity*sales.price) as max
from shops, sales
where sales.shop_id = shops.id
group by shops.id;

select view_sales.name as id_магазина, view_sales.max as сумма_продаж
from view_sales;

select shops.name as название, view_sales.max as вырученная_сумма
from view_sales, shops
where max = (
select max(max)
from view_sales)
and shops.id = view_sales.name;